### PR TITLE
add ui control for options dialog

### PR DESCRIPTION
**Pull request by myarjunar**
the options dialog:
Screen Shot 2019-03-26 at 15 03 15

the values stored in qgis settings:
Screen Shot 2019-03-26 at 15 04 51

### CODE REVIEW

**Comment by timlinux** [comment]
@myarjunar I tested it with EU (using US credentials) and it does not gracefully handle invalid credentials:

image

```
An error has occurred while executing Python code: 

Exception: Authentication failed. 
Traceback (most recent call last):
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/ui/widgets/options_dialog.py", line 75, in request_token
    use_testing_service=self.use_testing_service())
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/bridge_api_wrapper.py", line 86, in __init__
    raise Exception(self.authentication_message)
Exception: Authentication failed.
```

Can you please make sure it handles invalid credentials well.

Also @AndreLester can you ask GeoSYS for test credentials for EU so we can test both use cases. Please add them to the secrets file.

**Comment by timlinux** [comment]
Also failed against US:

image


I guess I need to check use testing service option... which works

image


But it should fail gracefully with no tracebacks...

**Comment by timlinux** [comment]
Another case that triggers a traceback:

An error has occurred while executing Python code: 

```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='identity.preprod.geosys-eu.com', port=443): Max retries exceeded with url: /v2.1/connect/token (Caused by ConnectTimeoutError(, 'Connection to identity.preprod.geosys-eu.com timed out. (connect timeout=10)')) 
Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (, 'Connection to identity.preprod.geosys-eu.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='identity.preprod.geosys-eu.com', port=443): Max retries exceeded with url: /v2.1/connect/token (Caused by ConnectTimeoutError(, 'Connection to identity.preprod.geosys-eu.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/ui/widgets/options_dialog.py", line 75, in request_token
    use_testing_service=self.use_testing_service())
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/bridge_api_wrapper.py", line 84, in __init__
    self.authenticated, self.authentication_message = self.authenticate()
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/bridge_api_wrapper.py", line 121, in authenticate
    self.username, self.password)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/bridge_api/connection.py", line 66, in get_access_token
    headers=headers, data=data, timeout=10)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/Maceira/python/plugins/geosys-qgis-plugin/geosys/bridge_api/api_abstract.py", line 121, in post
    response = post(url, **kwargs)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='identity.preprod.geosys-eu.com', port=443): Max retries exceeded with url: /v2.1/connect/token (Caused by ConnectTimeoutError(, 'Connection to identity.preprod.geosys-eu.com timed out. (connect timeout=10)'))
```

Screenshot 2019-03-25 at 22 24 42

I am also worried that you are still not using QGIS networking libs for network request handling. See here for an example of using QgsFileDownloader for fetching documents:

https://github.com/kartoza/SpeciesExplorer/blob/master/species_explorer/gbifutils.py

And then the QGIS docs on using QGIS API for network access:

* https://qgis.org/pyqgis/3.0/core/Network/QgsNetworkAccessManager.html
* https://qgis.org/pyqgis/3.0/core/Network/QgsNetworkContentFetcher.html
* https://qgis.org/pyqgis/3.0/core/Network/QgsNetworkContentFetcherTask.html (for fetching in a separate thread)
* https://qgis.org/pyqgis/3.0/core/File/QgsFileDownloader.html

**Comment by timlinux** [comment]
One more thing - we should have a sensible default for the paging limit - @AndreLester to check with the client as to what that should reasonably be. In the abscence of input from them lets go with 100?

**Comment by myarjunar** [comment]
@timlinux thanks for the comments.

- Sure, I am working on options dialog polishing (exception handling etc) and basic coverage control today.

- Currently, the layers dropdown I'm using is like how InaSAFE implement the layers dropdown. I will stick with this first until I finished the basic coverage control and then will do the polishing including that.

- also, does this mean we will put some kind of flag as a parameter for the API client which indicates what networking library to be used? 
```
To make the code more portable, we will design the library in such a way that the QGIS network
utility calls can be swapped for ‘pure python’ (e.g. using the “request” library) calls should a
developer wish to use the client library in a different context.
```

**Comment by AndreLester** [comment]
LGTM

**Pull request merged**
