### PR TITLE
handle multi polygon coverage request

### LINKED ISSUE #70: Multi polygon request
**Describe the bug**
When the layer contains several objects, the coverage is doing one coverage call with all objects. It should be one call per object.
Multifield request (one request with several object) is a nice to have feature that could be used in some specific case. If the number of object (in the layer or selection depending on the option selected) is under 10. Ideal would be to have Multifield as an option with a check box

### PR DESCRIPTION
**Pull request by myarjunar**
fix #70 

Screen Shot 2019-05-14 at 03 40 13

I added new checkbox option to combine all features into one geometry. If this option is unticked, then it will run multi polygon coverage request.

*applying this feature to processing algs will break the behaviour of the algs since its only expecting one output layer so it could be used by QGIS Modeler. cc @VincentLel @timlinux @AndreLester

### CODE REVIEW

**Comment by vincentlel** [comment]
Hi Rohmat, this is great, the label can be adapted to match our API documentation: Bulk request (all objects as a single geometry). Regarding the processing Algo, it means that we need to have one object per layer to make it works?

**Comment by myarjunar** [comment]
@VincentLel , I mean, if we enable multi polygon to the processing algs then we will have more than one output layer/map product (one layer per feature). If we have more than one output layer, we are no longer be able to use this processing algs in the graphical modeler tool. CMIIW @timlinux 
https://www.qgistutorials.com/en/docs/processing_graphical_modeler.html

**Comment by myarjunar** [comment]
@VincentLel I will merge this PR first. Should we ignore the case with the graphical modeler, I will create another PR to apply the multi-polygon request to the processing algorithm.

**Comment by timlinux** [comment]
LGTM thanks @myarjunar

**Pull request merged**
